### ISSUE TITLE
Why is PANYNJ not the default?

### ISSUE THREAD

**Issue by yspreen** [jamespfennell/path-train-gtfs-realtime#10]
It seems like using the official gov data source is a more robust and reliable data source. Any downsides to using it? Why is it not the default?

**Comment by jamespfennell** [comment]
Basically legacy reasons. When this project was first developed the only API was Matt Razza’s unofficial API. Eventually Sam figured out we could use the official data and added support for that. The plan at the time was to leave both soak for a while to verify the official data worked well…we never wrapped it up though.

If we are sure that the official data is good enough I think we could remove support for Matt Razza’s API.

**Comment by yspreen** [comment]
Thanks for the context.

I'm looking to add PATH data to my project, and I'm looking to pull the feed about every 30 seconds. I was going to spin up my own gtfs rt http server for it and hook into the official data source, hence the question. If you don't mind the added traffic of 1-2 machines polling twice a minute I'll happily plug it into the endpoint you're hosting. Do you have an opinion on that?

**Comment by jamespfennell** [comment]
You should definitely feel free to poll the endpoint I host! The software is pretty efficient and each poll request is basically free to handle.

**Comment by yspreen** [comment]
I'll close this, thank you! On a different note and while I have you here, do you store historical subway alert data? I saw you're running an archive site. Was wondering if you stored alerts or not. There was a day with an outage recently and I was curious if there was an alert for it and what it looked like

**Comment by jamespfennell** [comment]
Yeah I do have alerts data, perhaps for the last 3 years. I have it an unaggregated format so I would need to write some code to aggregate it daily and add it to subwaydata.nyc...let me see if I can throw something together over the weekend...

**Comment by yspreen** [comment]
Oh I mean I'm very much just interested in alerts between midnight and 12pm
on nov 16

**Comment by jamespfennell** [comment]
Sorry for the late response!

I have reconfigured subwaydata.nyc so that the raw GTFS data downloads also include the GTFS files for the NYC subway alerts feed going forward. I've also rerun the ETL pipeline for all of November, so all of the GTFS data downloads for November contain the raw GTFS alerts feed (https://subwaydata.nyc/explore-the-data). Is that helpful? Unfortunately you still need to parse the GTFS files to actually read the alerts. It would take a little more work to get the alerts into the CSV download.

For example, I downloaded the data for November 29. Then inside my locally checked out [gtfs repo](https://github.com/jamespfennell/gtfs) with Go installed I ran:

```
go run cmd/gtfs.go realtime ~/Downloads/subwaydatanyc_2024-11-29_gtfsrt_5f487ae60b0d/nycsubway_alerts_20241130T045507.499Z_cmdn76emr6em.gtfsrt
```

This actually gives back 311 alerts...for example

```
- AlertID lmm:alert:388344  Cause UNKNOWN_CAUSE  Effect UNKNOWN_EFFECT  Header Southbound [A][C] trains are running with delays after while we moved a train that had its brakes ac...
```

**Comment by yspreen** [comment]
I'm currently looking at the download for the 16th. I see plenty of gtfs files but I don't think I can spot the alert file in the archive?

**Comment by yspreen** [comment]
nevermind; I found them. there were just so many files that I scrolled right past them. found them with grep in format ./nycsubway_alerts_20241117T015057.051Z_4do66rvr6a2h.gtfsrt

**Comment by yspreen** [comment]
Thanks a ton @jamespfennell ! 

All GTFS data was offline during that time due to scheduled maintenance. I knew about it beforehand from the google group, and added an alert in my app. I wanted to see if I can detect these maintenance windows going forward without having to check the group and it does appear that there are alerts for this period. Not super detailed but it's there. 7 different messages for 7 different lines... would be better if they had one global alert. Oh well.

Thank you for providing this service!

**Comment by jamespfennell** [comment]
Glad it worked out!

It would be cool to not have to search through all the GTFS files, my idea is to add some code that reads all the alerts GTFS files and then provides a summary of all of the alerts. I'm guessing most of the alert GTFS files is just the same data...
