### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by jamespfennell** [jamespfennell/path-train-gtfs-realtime#6]
@cedarbaum I'm currently setting up continuous deployment for some of my projects and am thinking of doing it for the PATH train feed too. What this would mean is that after every successful CI run on the master branch (which includes pushing the Docker image to Docker hub) the `path.transitdata.nyc` job would be restarted automatically to run the new Docker image and incorporate the new changes. There would be up to a 2 minute lag between CI being green and job restarting.

I think this would be a nice QOL improvement, especially for this project where all of the changes recently have been committed by you and you have no other way of restarting the job. (Or maybe at this point you're running your own PATH train feed :) ). The only catch is that there is a tiny bit of responsibility to check the endpoint after a few minutes to make sure things haven't been broken by the most recent commit. What do you think?

**Comment by cedarbaum** [comment]
This sounds great to me! Agree that it would be good to have some basic health checks post-deployment. Not sure what your infra looks like, but maybe something like a readiness probe in k8s that waits for valid proto to be returned. If there is anything I can do to help, please let me know!

**Comment by jamespfennell** [comment]
Yeah…unfortunately the infrastructure is hand built so what I tend to do is manually check things work….eeeek! But it would be easy to add a check after redeploying that like a HTTP request to get the GTFS data succeeds. Also in general this project is pretty low risk to redeploy I think

**Comment by jamespfennell** [comment]
The status page (https://path.transitdata.nyc/) now has a build number to spot check if a redeployment after a push to master succeeded. I've also enabled automatic deployment for this project.
